<h1>Table of Contents<span class="tocSkip"></span></h1>
<div class="toc"><ul class="toc-item"></ul></div>

Изначально, я пытался применить NLP модели, или работать с нужными библиотеками. Но, с такой задачей я столкнулся первый раз, и, честно говоря, не смог найти информацию, какие использовать библиотеки. Поэтому написал скрипт вручную. Надеюсь, он будет работать корректно.

In [419]:
import pandas as pd

In [420]:
data = pd.read_csv('C:/Users/User/Downloads/test_data - test_data.csv')
data.head()

   dlg_id  line_n     role                                               text
0       0       0   client                                               Алло
1       0       1  manager                                  Алло здравствуйте
2       0       2   client                                        Добрый день
3       0       3  manager  Меня зовут ангелина компания диджитал бизнес з...
4       0       4   client                                                Ага

In [421]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 480 entries, 0 to 479
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   dlg_id  480 non-null    int64
 1   line_n  480 non-null    int64
 2   role    480 non-null    object
 3   text    480 non-null    object
dtypes: int64(2), object(2)
memory usage: 15.1+ KB

In [422]:
df = data.copy()

In [423]:
df

,dlg_id,line_n,role,text
0,0,0,client,Алло
1,0,1,manager,Алло здравствуйте
2,0,2,client,Добрый день
3,0,3,manager,Меня зовут ангелина компания диджитал бизнес з...
4,0,4,client,Ага
...,...,...,...,...
475,5,138,manager,По поводу виджетов и с ними уже обсудите конкр...
476,5,139,manager,Все я вам высылаю счет и с вами на связи если ...
477,5,140,client,Спасибо спасибо
478,5,141,client,Да да тогда созвонимся ага спасибо вам давайте
479,5,142,manager,Ну до свидания хорошего вечера

In [424]:
all_names = '''Авдей
Авксентий
Агапит
Агафон
Акакий
Акиндин
Александр
Алексей
Альберт
Альвиан
Анатолий
Андрей
Аникита
Антон
Антонин
Анфим
Аристарх
Аркадий
Арсений
Артём 
Артемий
Артур
Архипп
Афанасий
Богдан
Борис
Вавила
Вадим
Валентин
Валерий
Валерьян
Варлам
Варсонофий
Варфоломей 
Василий
Венедикт
Вениамин
Викентий
Виктор
Виссарион
Виталий
Владимир
Владислав
Владлен
Влас
Всеволод
Вячеслав
Гавриил
Галактион
Геласий
Геннадий
Георгий
Герасим
Герман
Германн
Глеб
Гордей
Григорий
Данакт
Даниил
Демид
Демьян
Денис
Дмитрий
Добрыня
Донат
Дорофей
Евгений
Евграф
Евдоким
Евсей
Евстафий
Егор
Емельян
Еремей
Ермолай
Ерофей
Ефим
Ефрем
Ждан
Зиновий
Иакинф
Иван
Игнатий
Игорь
Изот
Илья
Иннокентий
Ираклий
Ириней
Исидор
Иуда
Иулиан
Капитон
Ким
Кир
Кирилл
Климент
Кондрат
Конон
Константин
Корнилий
Кузьма
Куприян
Лаврентий
Лев
Леонид
Леонтий
Логгин
Лука
Лукий
Лукьян
Магистриан
Макар
Максим
Мамонт
Марк
Мартын
Матвей
Мелентий
Мина
Мирослав
Митрофан
Михаил
Мстислав
Назар
Нестор
Никандр
Никанор
Никита
Никифор
Никодим
Николай
Никон
Олег
Онисим
Онуфрий
Павел
Паисий
Панкратий
Пантелеймон
Парфений
Пафнутий
Пахомий
Пётр
Платон
Поликарп
Порфирий
Потап
Пров
Прокопий
Протасий
Прохор
Разумник
Родион
Родослав
Роман
Ростислав
Руслан
Савва
Савелий
Самуил
Святополк
Святослав
Севастьян
Семён
Серафим
Сергей
Сила
Сильвестр
Созон
Софрон
Спиридон
Станислав
Степан
Тарас
Тимофей
Тимур
Тит
Тихон
Трифон
Трофим
Урбан
Фаддей
Фёдор
Федосей
Федот
Феликс
Феоктист
Филат
Филимон
Филипп
Фирс
Фока
Фома
Фотий
Фрол
Харитон
Хрисанф
Христофор
Агафья
Аглая
Агния
Агриппина
Аза
Акулина
Алевтина
Александра
Алина
Алла
Анастасия
Ангелина
Анжела
Анжелика
Анна
Антонина
Анфиса
Валентина
Валерия
Варвара
Василиса
Вера
Вероника
Виктория
Галина
Глафира
Гликерия
Дана
Дарья
Евгения
Евдокия
Евлалия
Евлампия
Евпраксия
Евфросиния
Екатерина
Елена
Елизавета
Епистима
Ермиония
Жанна
Зинаида
Злата
Зоя
Инга
Инесса
Инна
Иоанна
Ираида
Ирина
Ия
Капитолина
Карина
Каролина
Кира
Клавдия
Ксения
Лада
Лариса
Лидия
Лилия
Любовь
Людмила
Маргарита
Марина
Мария
Марфа
Матрёна
Милица
Мирослава
Надежда
Наталья
Нина
Нонна
Оксана
Октябрина
Олимпиада
Ольга
Павлина
Пелагея
Пинна
Полина
Прасковья
Рада
Раиса
Регина
Римма
Рогнеда
Руслана
Светлана
Серафима
Снежана
София
Таисия
Тамара
Татьяна
Улита
Ульяна
Урсула
Фаина
Феврония
Фёкла
Феодора
Целестина
Юлия
Яна
Ярослава'''
all_names = all_names.lower()
all_names = all_names.split()
all_names

['авдей',
 'авксентий',
 'агапит',
 'агафон',
 'акакий',
 'акиндин',
 'александр',
 'алексей',
 'альберт',
 'альвиан',
 'анатолий',
 'андрей',
 'аникита',
 'антон',
 'антонин',
 'анфим',
 'аристарх',
 'аркадий',
 'арсений',
 'артём',
 'артемий',
 'артур',
 'архипп',
 'афанасий',
 'богдан',
 'борис',
 'вавила',
 'вадим',
 'валентин',
 'валерий',
 'валерьян',
 'варлам',
 'варсонофий',
 'варфоломей',
 'василий',
 'венедикт',
 'вениамин',
 'викентий',
 'виктор',
 'виссарион',
 'виталий',
 'владимир',
 'владислав',
 'владлен',
 'влас',
 'всеволод',
 'вячеслав',
 'гавриил',
 'галактион',
 'геласий',
 'геннадий',
 'георгий',
 'герасим',
 'герман',
 'германн',
 'глеб',
 'гордей',
 'григорий',
 'данакт',
 'даниил',
 'демид',
 'демьян',
 'денис',
 'дмитрий',
 'добрыня',
 'донат',
 'дорофей',
 'евгений',
 'евграф',
 'евдоким',
 'евсей',
 'евстафий',
 'егор',
 'емельян',
 'еремей',
 'ермолай',
 'ерофей',
 'ефим',
 'ефрем',
 'ждан',
 'зиновий',
 'иакинф',
 'иван',
 'игнатий',
 'игорь',
 'изот',
 'илья',
 'иннокентий',
 'ираклий',
 'ириней',
 'исидор',
 'иуда',
 'иулиан',
 'капитон',
 'ким',
 'кир',
 'кирилл',
 'климент',
 'кондрат',
 'конон',
 'константин',
 'корнилий',
 'кузьма',
 'куприян',
 'лаврентий',
 'лев',
 'леонид',
 'леонтий',
 'логгин',
 'лука',
 'лукий',
 'лукьян',
 'магистриан',
 'макар',
 'максим',
 'мамонт',
 'марк',
 'мартын',
 'матвей',
 'мелентий',
 'мина',
 'мирослав',
 'митрофан',
 'михаил',
 'мстислав',
 'назар',
 'нестор',
 'никандр',
 'никанор',
 'никита',
 'никифор',
 'никодим',
 'николай',
 'никон',
 'олег',
 'онисим',
 'онуфрий',
 'павел',
 'паисий',
 'панкратий',
 'пантелеймон',
 'парфений',
 'пафнутий',
 'пахомий',
 'пётр',
 'платон',
 'поликарп',
 'порфирий',
 'потап',
 'пров',
 'прокопий',
 'протасий',
 'прохор',
 'разумник',
 'родион',
 'родослав',
 'роман',
 'ростислав',
 'руслан',
 'савва',
 'савелий',
 'самуил',
 'святополк',
 'святослав',
 'севастьян',
 'семён',
 'серафим',
 'сергей',
 'сила',
 'сильвестр',
 'созон',
 'софрон',
 'спиридон',
 'станислав',
 'степан',
 'тарас',
 'тимофей',
 'тимур',
 'тит',
 'тихон',
 'трифон',
 'трофим',
 'урбан',
 'фаддей',
 'фёдор',
 'федосей',
 'федот',
 'феликс',
 'феоктист',
 'филат',
 'филимон',
 'филипп',
 'фирс',
 'фока',
 'фома',
 'фотий',
 'фрол',
 'харитон',
 'хрисанф',
 'христофор',
 'агафья',
 'аглая',
 'агния',
 'агриппина',
 'аза',
 'акулина',
 'алевтина',
 'александра',
 'алина',
 'алла',
 'анастасия',
 'ангелина',
 'анжела',
 'анжелика',
 'анна',
 'антонина',
 'анфиса',
 'валентина',
 'валерия',
 'варвара',
 'василиса',
 'вера',
 'вероника',
 'виктория',
 'галина',
 'глафира',
 'гликерия',
 'дана',
 'дарья',
 'евгения',
 'евдокия',
 'евлалия',
 'евлампия',
 'евпраксия',
 'евфросиния',
 'екатерина',
 'елена',
 'елизавета',
 'епистима',
 'ермиония',
 'жанна',
 'зинаида',
 'злата',
 'зоя',
 'инга',
 'инесса',
 'инна',
 'иоанна',
 'ираида',
 'ирина',
 'ия',
 'капитолина',
 'карина',
 'каролина',
 'кира',
 'клавдия',
 'ксения',
 'лада',
 'лариса',
 'лидия',
 'лилия',
 'любовь',
 'людмила',
 'маргарита',
 'марина',
 'мария',
 'марфа',
 'матрёна',
 'милица',
 'мирослава',
 'надежда',
 'наталья',
 'нина',
 'нонна',
 'оксана',
 'октябрина',
 'олимпиада',
 'ольга',
 'павлина',
 'пелагея',
 'пинна',
 'полина',
 'прасковья',
 'рада',
 'раиса',
 'регина',
 'римма',
 'рогнеда',
 'руслана',
 'светлана',
 'серафима',
 'снежана',
 'софия',
 'таисия',
 'тамара',
 'татьяна',
 'улита',
 'ульяна',
 'урсула',
 'фаина',
 'феврония',
 'фёкла',
 'феодора',
 'целестина',
 'юлия',
 'яна',
 'ярослава']

In [425]:
df=df[df['role']=='manager']
df = df.reset_index(drop=True)
df.text = df.text.str.lower()

In [426]:
results = pd.DataFrame(columns=['id разговора', 'Поздоровался', 'Представился(реплика)', 
                                'Назвал имя', 'Назвал компанию', 'Попрощался', 'И попрощался и поздоровался'], 
                       index=range(6))
results

,id разговора,Поздоровался,Представился(реплика),Назвал имя,Назвал компанию,Попрощался,И попрощался и поздоровался
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [427]:
for id in set(df.dlg_id):
    a = df[df['dlg_id']<id+1]
    a = a[a['dlg_id']>=id] 
    b = []
    sliced_df = a.head(2)
    sliced_df = sliced_df.append(df.tail(2))
    sliced_df
    greeting = 0
    introduce = 0
    mng_name = 0
    company = 0
    farewell = 0
    results['id разговора'][id]=id
    for i in sliced_df.text:
        b.append(i.split())
    for i in b:
        if 'здравствуйте' in i:
            print('Менеджер, с id разговора {} поздоровался фразой:'.format(id), *i)
            greeting+=1
            print()
            results['Поздоровался'][id]='Да'
        elif 'добрый' and 'день' in i:
            print('Менеджер, с id разговора {} поздоровался фразой:'.format(id), *i)
            greeting+=1
            print()
            results['Поздоровался'][id]='Да'
        elif 'меня' in i and 'зовут' in i:
            print('Менеджер, с id разговора {} представился фразой:'.format(id), *i)
            print()
            introduce+=1
            results['Представился(реплика)'][id]='Да'
            for name in all_names:
                if name in i:
                    print('Менеджерa, с id разговора {} зовут:'.format(id), name)
                    print()
                    mng_name+=1
                    results['Назвал имя'][id]='Да'
            for k in b:
                for kk in range(len(k)):
                    if k[kk]=='компания':
                        print('Менеджерa, с id разговора {} работает в компании:'.format(id), k[kk+1])
                        print()
                        company+=1
                        results['Назвал компанию'][id]='Да'
        elif 'хорошего' in i:
            print('Менеджер, с id разговора {} попрощался фразой:'.format(id), *i)
            farewell+=1
            results['Попрощался'][id]='Да'
            print()
        elif 'до' in i and 'свидания' in i:
            print('Менеджер, с id разговора {} попрощался фразой:'.format(id), *i)
            farewell+=1
            results['Попрощался'][id]='Да'
            print()
    if greeting>=1 and farewell>=1:
        print('Менеджер, с id разговора {} поздоровался и попрощался с клиентом'.format(id))
        results['И попрощался и поздоровался'][id]='Да'
    if greeting<1:
        print('Менеджер, с id разговора {} не поздоровался с клиентом'.format(id))
    if introduce<1:
        print('Менеджер, с id разговора {} не представился'.format(id))
    if mng_name<1:
        print('Менеджер, с id разговора {} не назвал свое имя'.format(id))
    if company<1:
        print('Менеджер, с id разговора {} не назвал свою компанию'.format(id))
    if farewell<1:
        print('Менеджер, с id разговора {} не назвал не попрощался с клиентом'.format(id))
    print()
    print()
    print()

Менеджер, с id разговора 0 поздоровался фразой: алло здравствуйте

Менеджер, с id разговора 0 представился фразой: меня зовут ангелина компания диджитал бизнес звоним вам по поводу продления лицензии а мы с серым у вас скоро срок заканчивается

Менеджерa, с id разговора 0 зовут: ангелина

Менеджерa, с id разговора 0 работает в компании: диджитал

Менеджер, с id разговора 0 попрощался фразой: ну до свидания хорошего вечера

Менеджер, с id разговора 0 поздоровался и попрощался с клиентом



Менеджер, с id разговора 1 поздоровался фразой: алло здравствуйте

Менеджер, с id разговора 1 представился фразой: меня зовут ангелина компания диджитал бизнес звоню вам по поводу продления а мы сели обратила внимание что у вас срок заканчивается

Менеджерa, с id разговора 1 зовут: ангелина

Менеджерa, с id разговора 1 работает в компании: диджитал

Менеджер, с id разговора 1 попрощался фразой: ну до свидания хорошего вечера

Менеджер, с id разговора 1 поздоровался и попрощался с клиентом



Менеджер, с id разговора 2 поздоровался фразой: алло здравствуйте

Менеджер, с id разговора 2 представился фразой: меня зовут ангелина компания диджитал бизнес звоню вам по поводу продления лицензии а мастера мы с вами сотрудничали по видео там

Менеджерa, с id разговора 2 зовут: ангелина

Менеджерa, с id разговора 2 работает в компании: диджитал

Менеджер, с id разговора 2 попрощался фразой: ну до свидания хорошего вечера

Менеджер, с id разговора 2 поздоровался и попрощался с клиентом



Менеджер, с id разговора 3 поздоровался фразой: алло дмитрий добрый день

Менеджер, с id разговора 3 представился фразой: добрый меня максим зовут компания китобизнес удобно говорить

Менеджерa, с id разговора 3 зовут: максим

Менеджерa, с id разговора 3 работает в компании: китобизнес

Менеджер, с id разговора 3 попрощался фразой: ну до свидания хорошего вечера

Менеджер, с id разговора 3 поздоровался и попрощался с клиентом



Менеджер, с id разговора 4 попрощался фразой: ну до свидания хорошего вечера

Менеджер, с id разговора 4 не поздоровался с клиентом
Менеджер, с id разговора 4 не представился
Менеджер, с id разговора 4 не назвал свое имя
Менеджер, с id разговора 4 не назвал свою компанию



Менеджер, с id разговора 5 попрощался фразой: ну до свидания хорошего вечера

Менеджер, с id разговора 5 не поздоровался с клиентом
Менеджер, с id разговора 5 не представился
Менеджер, с id разговора 5 не назвал свое имя
Менеджер, с id разговора 5 не назвал свою компанию

In [428]:
results = results.fillna('Нет')
results

,id разговора,Поздоровался,Представился(реплика),Назвал имя,Назвал компанию,Попрощался,И попрощался и поздоровался
0,0,Да,Да,Да,Да,Да,Да
1,1,Да,Да,Да,Да,Да,Да
2,2,Да,Да,Да,Да,Да,Да
3,3,Да,Да,Да,Да,Да,Да
4,4,Нет,Нет,Нет,Нет,Да,Нет
5,5,Нет,Нет,Нет,Нет,Да,Нет